# Generated by Django 4.2.4 on 2023-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('landmark', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('assign_driver_email', models.EmailField(max_length=254, null=True)),
                ('loadtype', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True)),
                ('cycle_period', models.CharField(max_length=30, null=True)),
                ('best_route', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
