# Generated by Django 4.2.4 on 2023-11-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_bin',
            name='landmark',
        ),
        migrations.AddField(
            model_name='create_bin',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='create_bin',
            name='cycle_period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Twice', 'Twice'), ('Weekly', 'Weekly')], max_length=30, null=True),
        ),
    ]
